name: Feature Request
description: Suggest an idea for aptprep
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - nickguletskii
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe how this feature would be used and who would benefit from it.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation details
      description: If you have ideas about how this could be implemented, please share them.
    validations:
      required: false

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking changes
      description: Would this feature require breaking changes?
      options:
        - label: This feature would require breaking changes to existing functionality
        - label: This feature could be implemented without breaking changes

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.rust-lang.org/policies/code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
